#!/usr/bin/env zsh

__fm-open-dialog() {
    local -P color=$1 title=$2 elements=$3
    {
        tput smcup
        tput home
        tput csr 1 $(( $(tput lines)-1 ))
        print -P -- "%F{${color:1}%S%B  ${(r:(($COLUMNS-15)):)title}  %b\^C Cancel  %s%f"
        if [[ $elements ]]; then
            __fm-print-recap $color $elements $FM_MAX_DIALOG_RECAP
        else
            __fm-print $color "Working Dir: $PWD"
        fi
        print
    } > /dev/tty
}
