#!/usr/bin/env zsh

_fm-print-recap() {
    local -P color=$1 elements=( ${(P)${2}} ) limit=$3 element n=1 fmt
    if [[ $limit -le 0 ]]; then
        return 0
    elif [[ $limit -eq 1 && $#elements -gt 1 ]]; then
        _fm-print $color "$#elements Selected Elements in Total"
        return 0
    elif [[ $limit -lt $#elements ]]; then
        ((limit-=1))
    fi
    for element in $elements[1,$limit]
        _fm-print $color "${(l:$#limit:)$((n++))}. $element"
    if [[ $limit -lt $#elements ]] \
        _fm-print $color "...and $(($#elements-$limit)) more, for a Total of $#elements"
}
