#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__close-dialog() {
	local -P sleep_time=${1:-1} note res=$?

	if [[ $TRY_BLOCK_INTERRUPT -gt 0 ]]; then
		TRY_BLOCK_INTERRUPT=0
		note=' [INTERRUPTED]'
	elif [[ $res -gt 0 ]]; then
		note=" [ERROR $res]"
	fi

	fm__notify "$num $message$note"
	fm__print -magenta "\n$num $message$note" > /dev/tty
	sleep $sleep_time

	tput csr 0 $(tput lines)
}
