#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__print-recap() {
	local -P color=$1 elements=( ${(P)${2}} ) limit=$3 element n=1 fmt
	if [[ $limit -le 0 ]]; then
		return 0
	elif [[ $limit -eq 1 && $#elements -gt 1 ]]; then
		fm__print $color "$#elements Selected Elements in Total"
		return 0
	elif [[ $limit -lt $#elements ]]; then
		((limit-=1))
	fi
	for element in $elements[1,$limit]
		fm__print $color "${(l:$#limit:)$((n++))}. $element"
	if [[ $limit -lt $#elements ]] \
			fm__print $color "...and $(($#elements-$limit)) more, for a Total of $#elements"
}
