#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__print() {
	local -P noend
	if [[ $1 == -n ]] { noend=$1 ; shift }
	print $noend -- ${(%):-%F{${1:1}}}$2${(%):-%f}
}
