#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


setopt EXTENDED_GLOB

local fnc dir=${fm__root:-${0:A:h}}
for fnc in $dir/autoload/**/^*.zwc(.N); zcompile -Uz $fnc
for fnc in $dir/preview/^*.zwc(.N); zcompile -Uz $fnc
