#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


setopt EXTENDED_GLOB

local fnc dir=${fm__root:-$PWD}
for fnc in $dir/autoload/**/^*.zwc(.); zcompile -Uz $fnc
for fnc in $dir/preview/^*.zwc(.); zcompile -Uz $fnc
