#!/usr/bin/env zsh

__fm-select() {
    clipboard[mode]=$1
    __fm-reduce-items
    clipboard[sources]=${(@F)items}
    __fm-write -tmp clipboard
    print
    __fm-notify "$#items Items $clipboard[mode]"
}
