#!/usr/bin/env zsh

__fm-run-added() {
    setopt LOCAL_OPTIONS ERR_RETURN
    local -P menu elements=() res
    {
        for menu in $added_menu; do
            elements=( "${(ps|\t|)menu}" )
            if [[ $elements[5] == $key || $elements[3] == $key ]] eval $elements[2]
        done
    } always {
        res=$?
        if [[ $res -gt 0 ]] __fm-notify "Added Tool failed [ERROR $res]"
    }
}
