#!/usr/bin/env zsh

__fm-dest-name() {
    local -P n=1 suffix=$1 ext root
    if [[ -d $source || $name == .* || $name == *. || $name != *.* ]]; then
        root=$name
    else
        ext=.$name:e
        root=$name:r
    fi
    while [[ -e $name ]]; do
        if [[ $n -eq 1 ]]; then
            name=${root}($suffix)$ext
        else
            name=${root}($suffix-$n)$ext
        fi
        ((n+=1))
    done
}
