#!/usr/bin/env zsh

__fm-remove() {
    setopt LOCAL_OPTIONS ERR_RETURN
    local -P item sudo name yn
    local num=0 message='Items removed'
    __fm-open-dialog -red 'Remove Selected Items' items
    {
        for item in $items; do
            name=$item:t
            if [[ -w $item:h ]] { sudo='' } else { sudo=$FM_CMD_SUDO }
            __fm-print -n -red "Remove $name? (y/n)> "
            if read -q yn; then
                print ; $=sudo rm -rf $item
                ((num+=1))
                __fm-print -red 'Removed!'
            else
                __fm-print -yellow '\nSkippeed!'
                continue
            fi
        done
    } always {
        __fm-close-dialog
    }
}
