#!/usr/bin/env zsh

fm::open() {
    if [[ -z $FM_CMD_OPEN ]] { fm::notify 'No FM_CMD_OPEN command found'; return 0 }
    for item in $items
        sh -i -c "$=FM_CMD_OPEN ${(q)item} &" || fm::notify "Cannot open $item [ERROR $?]"
}
