#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__reduce-items
targets=( $items )
fm__write -tmp targets
fm__notify "$#targets Targets marked"
