#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


# remove redundant childs of already included parent dirs
fm__reduce-items() {
	local -P item
	for item in $items
		items=( ${items:#$item/*} )
}
