#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__open() {
	if [[ -z $FM__CMD_OPEN ]] { fm__notify 'No FM__CMD_OPEN command found'; return 0 }
	for item in $items
		sh -i -c "$=FM__CMD_OPEN ${(q)item} &" || fm__notify "Cannot open $item [ERROR $?]"
}
