#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__cd() {
	local -P dir=$1:a
	recent_dirs=( $dir ${recent_dirs:#$dir} )
	fm__write -data recent_dirs
	cd $dir
	query=''
	view=$fs_view
}
