#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__new-shell() {
	setopt LOCAL_OPTIONS ERR_RETURN
	local -P res
	{
		if [[ $TMUX ]]; then
			tmux new-window -c $PWD -n "dir $PWD:t"
		elif [[ $FM__CMD_TERMINAL ]]; then
			$=FM__CMD_TERMINAL $PWD &>/dev/null &!
		elif [[ $FM__CMD_SHELL ]]; then
			print "Opening a new '$FM__CMD_SHELL' session here. Type 'exit' to return to the FM Panel..."
			$=FM__CMD_SHELL
		else
			fm__notify 'No suitable command for opening a new shell found'
			return 0
		fi
	} always {
		res=$?
		if [[ $res -gt 0 ]] fm-notify "New Shell Tool failed [ERROR $res]"
	}
}
