#!/usr/bin/env zsh

__fm-toggle-hidden() {
    if $hidden; then
        hidden=false
        __fm-notify 'Hidden Visibility OFF'
    else
        hidden=true
        __fm-notify "Hidden Visibility ON"
    fi
    if [[ $view == GREP ]]; then
        query=$rg_query
        __fm-set-grep
    fi
}
