#!/usr/bin/env zsh

_fm-toggle-hidden() {
    if $hidden; then
        hidden=false
        _fm-notify 'Hidden Visibility OFF'
    else
        hidden=true
        _fm-notify "Hidden Visibility ON"
    fi
    if [[ $view == GREP ]]; then
        query=$rg_query
        _fm-set-grep
    fi
}
