#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


local -P cmd
for cmd; do
	type ${cmd%% *} &>/dev/null && { print -- $cmd; return 0 }
done
return 1
