#!/usr/bin/env zsh

fm__toggle-hidden() {
    if $hidden; then
        hidden=false
        fm__notify 'Hidden Visibility OFF'
    else
        hidden=true
        fm__notify "Hidden Visibility ON"
    fi
    if [[ $view == GREP ]]; then
        query=$rg_query
        fm__set-grep
    fi
}
