#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__write() {
	typeset -p $2 > ${(P)${:-FM__${(U)1:1}}}/$2
}
