#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


if [[ -z $FM__CMD_SORT ]] { fm__notify "No FM__CMD_SORT command found"; return 0 }
sort=true
fm__notify "Items temporarily sorted by path"
