#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__cycle-preview() {
	((preview[$1]+=1))
	if [[ $preview[$1] -gt $#FM__PREVIEW_MODES ]] preview[$1]=1
	fm__write -data preview
}
