#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


print -- ${(%):-%F{$FM__INFO_COLOR}%B%S $view %s%b%B}${(D)PWD}${(%):-%b%f}' '
