#!/usr/bin/env zsh

fm__widget() {
    setopt LOCAL_OPTIONS NO_SH_WORD_SPLIT EXTENDED_GLOB PIPE_FAIL NO_POSIX_IDENTIFIERS
    if [[ $CONTEXT == vared ]] return 0
    local fs_view=DIR view=DIR fm_mode=widget
    local hidden=false sort=false
    local rg_query rg_message
    local -a recent_dirs header=()
    local -A preview
    fm__read -data preview
    fm__read -data recent_dirs
    recent_dirs=( $PWD ${recent_dirs:#$PWD} )
    fm__write -data recent_dirs

    tput cud1
    LBUFFER+=$( fm__panel-start )
    local -P res=$?
    tput cuu1
    [[ $widgets[autosuggest-clear] ]] && zle autosuggest-clear
    zle redisplay
    typeset -f zle-line-init > /dev/null && zle zle-line-init
    return $res
}
