#!/usr/bin/env zsh

_fm-view-fav(){
    local -P fav_lines=("${(@f)$(<$FM_DATA/favorites)}") line length max_length name fav_path ln=1 broken=()

    for line in $fav_lines; do
        length=${#${line:8}%%=*}
        if [[ $length > $max_length ]] max_length=$length
    done
    for line in $fav_lines; do
        line=${line:8}
        name=${line%%=*} fav_path=${line#*=}
        if  [[ -d $fav_path ]]; then
            _fm-print -blue "$ln  ${(r:$max_length:)name}  $fav_path"
        elif [[ -f $fav_path ]]; then
            print -- "$ln  ${(r:$max_length:)name}  $fav_path"
        else
            broken+=$ln
        fi
        ((ln+=1))
    done |
        if [[ $sort == true && $FM_CMD_SORT ]]; then
            LC_ALL=C $=FM_CMD_SORT -k3
        else
            >&1
        fi

    _fm-fav-rm $broken
}
