#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__view-rec() {
	local -P dir
	fm__read -data recent_dirs
	for dir in $recent_dirs
		if [[ ! -d $dir ]] recent_dirs=( ${recent_dirs:#$dir} ) # removes deleted recent_dirs dirs
	recent_dirs=( ${recent_dirs:0:$FM__MAX_RECENT_DIRS} ) # prune
	fm__write -data recent_dirs
	for dir in ${recent_dirs:1}; do
		fm__print -blue $dir
	done |
		if [[ $sort == true && $FM__CMD_SORT ]]; then
			LC_ALL=C $=FM__CMD_SORT
		else
			>&1
		fi
}
