#!/usr/bin/env zsh

fm__view-find() {
	case $FM__CMD_FIND in
		fd*)
			case $hidden in
				true)  $=FM__CMD_FIND -uu . ;;
				false) $=FM__CMD_FIND     . ;;
			esac
			;;
		find*)
			case $hidden in
				true)  $=FM__CMD_FIND  ;;
				false) $=FM__CMD_FIND . -path '*/.*' -prune -o -print ;;
			esac 2>/dev/null | sed 's/\.\///'
			;;
	esac |
		if [[ $sort == true && $FM__CMD_SORT ]]; then
			LC_ALL=C $=FM__CMD_SORT
		else
			>&1
		fi
}
