#!/usr/bin/env zsh

__fm-fav-add() {
    setopt LOCAL_OPTIONS ERR_RETURN
    local list=(${1:-$items}) num=0 message='Favorites added' name=''
    local -P item
    __fm-open-dialog -green 'Add Selected Favorites' list
    {
        for item in $list; do
            name=$item:t && __fm-fav-accept-name -green
            if [[ -z $name ]] { __fm-print -yellow 'Skipped!' ; continue }
            print "hash -d ${name}=${(q)item}" >> $FM_DATA/favorites
            ((num+=1))
            __fm-print -green 'Added!'
        done

        if [[ $num -gt 0 ]] { source $FM_DATA/favorites ; view=FAV }
    } always {
        __fm-close-dialog
    }
}
