#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__fav-rm() {
	if [[ $# -eq 0 ]] return 0
	sed -i ${(j|d;|)@}d $FM__DATA/favorites
	hash -drf
	source $FM__DATA/favorites
}
