#!/usr/bin/env zsh

# Copyright (c) 2021-2026 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


if [[ $# -eq 0 ]] return 0
sed -i ${(j|d;|)@}d $FM__DATA/favorites
hash -drf
source $FM__DATA/favorites
