#!/usr/bin/env sh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


set -e

if [ $(id -u) = 0 ]; then
   echo 'This script is not supposed to be run as root!'
   exit
fi

root="$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)")"

fm_name='try-fm'
context=${TRY_FM_CONTEXT:-https://github.com/ddnexus/fm.git#master:try-fm/docker}

fm_image="$fm_name"
fm_vol='try_fm_user_home'
zsh_image='zshusers/zsh:5.8'

script_file="$root/$fm_name"
vol_file="$root/.${fm_name}_vol"
zsh_file="$root/.${fm_name}_zsh"

check_docker() {
	if ! docker info 1>/dev/null 2>&1; then
		echo "Docker is not running!"
		exit
	fi
}

case "$1" in
	start|s)
		check_docker

		# try-fm not present
		if ! docker image inspect $fm_image 1>/dev/null 2>&1; then

			# prevent removing the zsh_image when it was already present before fm-try
			if docker image inspect $zsh_image 1>/dev/null 2>&1; then
				touch "$zsh_file"
			fi

			cat <<-BUILDING

				================================= BUILD IMAGE =================================
				IMPORTANT: This installation will not change your system in any way.
				All the packages/plugins will be installed and relegated in the docker space.
				This environment has also a lot of not required stuff that is very cool to try.
				You can completely purge everything with '~/$fm_name purge' when you are done.
				===============================================================================
			BUILDING
			read -p "Press enter to start... " input

			DOCKER_BUILDKIT=0 docker build \
					--tag $fm_image \
					--build-arg user="$(id -un)" \
					--build-arg uid=$(id -u) \
					--build-arg gid=$(id -g) \
					--build-arg term="$TERM" \
					$context

			echo "The '$fm_name' docker image has been built!"
		fi

		# end building / start running

		cat <<-CAVEATS

			================================= CAVEATS =====================================
			* FM uses the alt/option key as meta character in many shortcuts. If the alt
			  key does not work as a shortcut modifier, then read the solution in the Q&A:
			  https://github.com/ddnexus/fm/tree/master/try-fm#Q&A
		CAVEATS

		case "$(uname -s)" in
			Linux*)
				x11_mount="--env DISPLAY --volume /tmp/.X11-unix:/tmp/.X11-unix:rw"
				;;
			Darwin*)
				cat <<-CAVEATS
				* The FIND view (alt-f) may be very slow in docker bind mounted paths:
				  that will work super fast when FM will be installed and run directly
				CAVEATS
				;;
			CYGWIN*)  : ;;
			MINGW*)   : ;;
			*)        : ;;
		esac

		case "$2" in
			--root-mount|-r|'')
				warning="* Your own filesystem will be writable and mounted at /$(hostname)
* Your original home dir will be writable and available at /$(hostname)$HOME"
				host_mount="--volume /:/$(hostname) --workdir /$(hostname)$HOME"
				;;
			--home-mount|-h)
				warning="* Your original home dir will be writable and available at /$(hostname)-$USER"
				host_mount="--volume $HOME:/$(hostname)-$USER --workdir /$(hostname)-$USER"
				;;
			--no-mount|-n)
				warning=''
				host_mount=''
				;;
			*)
				echo "The option '$2' is not supported"
				exit
				;;
		esac

		cat <<-INFO

			============================== IMPORTANT INFO =================================
			Starting a zsh shell session in the '$fm_name' docker container...
			* Session Login: $USER   Password: fm
			* The HOME in the docker container will be /home/$USER
			* Edit the /home/$USER/.zshrc to experiment with it
			* Your changes in /home/$USER will survive rebooting
			* You can reset /home/$USER by running '~/$fm_name reset' after exiting
			  the docker session
			* You can reclaim your disk space by removing all the docker objects related
			  to '$fm_name' by running '~/$fm_name purge' after exiting the docker session

			=============================== BASIC USAGE ===================================
			* Run the fm command to start, then press 'ctrl-space' to get the menu with
			  the inline documentation.
			* Quit FM or the widget with 'ctrl-q', 'ctrl-c' or 'esc'
			* Exit from the docker session with the usual 'exit'
			* You can get the widget by pressing 'alt-f' twice (rapidly) in the zsh prompt
		INFO

		if [ -n "$warning" ]; then
			cat <<-WARNING

				%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% !!! WARNING !!! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
				FM and this demo is safe and requires you to confirm deletions and enter the
				sudo password for protected items, however:
				$warning
				Don't do anything stupid with your own files.
				If you want to try deletions, create dummy files first ;)
				%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
			WARNING
		fi

		if ! [ -e "$vol_file" ]; then # confirm only once
			echo
			read -p "Press enter to confirm that you have read and understood the above messages... " input
			touch "$vol_file"
		fi

		docker run \
				--name $fm_name \
				--volume $fm_vol:/home/$USER \
				--interactive \
				--tty \
				--rm \
				$x11_mount \
				$host_mount \
				$fm_image
				;;

	reset|r)
		check_docker
		read -p "Reset HOME and plugins? (y/n)> " input
		if [ "$input" = y ] || [ "$input" = Y ]; then
			echo "Removing the '$fm_vol' docker volume..."
			docker volume rm $fm_vol
			rm -f "$vol_file"
			echo "Reset done. You can start the '$fm_name'"
		fi
		;;

	purge|p)
		check_docker
		read -p "Purge everything related to '$fm_name' from your system? (y/n)> " input
		if [ "$input" = y ] || [ "$input" = Y ]; then
			if [ -e "$zsh_file" ]; then
				docker rmi $fm_image
			else
				docker rmi $fm_image $zsh_image
			fi
			docker volume rm $fm_vol
			if [ "$(printf '%-.1s\n' "$context")" = '/' ]; then
				rm -fv "$vol_file"
			else
				rm -fv "$script_file" "$vol_file" "$zsh_file"
			fi
			echo "'$fm_name' has been completely purged from your system!"
		fi
		;;

	usage|help|u|h|'')
		cat <<-USAGE

			==================================== USAGE ====================================
			~/$fm_name start|s    Setup and start the docker session...
			 [--root-mount|-r]  ...with default mount of / at /$(hostname)
			  --home-mount|-m   ...with mount of $HOME at /$(hostname)-$USER only
			    --no-mount|-n   ...with no mount

			~/$fm_name reset|r    Reset so the next start will restore HOME and plugins
			~/$fm_name purge|p    Purge everything related to '$fm_name' from your system
			~/$fm_name usage|u    Show this screen
			===============================================================================
		USAGE
		;;

	*)
		echo "The subcommand '$1' is not supported!"
		;;
esac
