#!/usr/bin/env zsh

_fm-cmd-env() {
    local -P var variables=(
    # FM UI
        FM_KEY_MENU
        FM_KEY_PREVIEW
        FM_KEY_SELECT_ALL
        FM_KEY_REFRESH
        FM_KEY_NOTIFY_WD
        FM_KEY_HIDDEN
        FM_KEY_SORT
        FM_KEY_QUIT
    # FM Views
        FM_KEY_VIEW_ITEM
        FM_KEY_VIEW_DIR
        FM_KEY_VIEW_FIND
        FM_KEY_VIEW_GREP
        FM_KEY_VIEW_REC
        FM_KEY_VIEW_FAV
    # FS Navigation
        FM_KEY_CD_HOME
        FM_KEY_CD_ROOT
        FM_KEY_CD_PARENT
        FM_KEY_CD_LAST
        FM_KEY_CD_CONTAIN
        FM_KEY_CD_START
    # FS Commands
        FM_KEY_NEW_FILE
        FM_KEY_NEW_DIR
        FM_KEY_COPY
        FM_KEY_CUT
        FM_KEY_PASTE
        FM_KEY_FAV_ADD_WD
        FM_KEY_FAV_ADD
        FM_KEY_MARK
        FM_KEY_LINK
        FM_KEY_RENAME
        FM_KEY_REMOVE
        FM_KEY_EXEC_ON
        FM_KEY_EXEC_OFF
    # Tools
        FM_KEY_OPEN
        FM_KEY_EDIT
        FM_KEY_NEW_SHELL
        FM_KEY_COPY_PATH
    # CMD vars
        FM_CMD_CAT
        FM_CMD_LS
        FM_CMD_FIND
        FM_CMD_EDIT
        FM_CMD_OPEN
        FM_CMD_PAGER
        FM_CMD_RIPGREP
        FM_CMD_TERMINAL
        FM_CMD_SHELL
        FM_CMD_XCLIP
        FM_CMD_SUDO
        FM_CMD_STAT
        FM_CMD_SORT
    # Other vars
        FM_MAX_GREP_FILES
        FM_MAX_RECENT_DIRS
        FM_MAX_DIALOG_RECAP
        FM_MAX_MENU_RECAP
        FM_MENU_WIDTH
        FM_HINTS
        FM_INFO_COLOR
        FM_PREVIEW_MODES
        FM_COMMAND_FZF_OPTS
        FM_WIDGET_FZF_OPTS
        FM_DATA
    # Internal vars
        _fm_version
        _fm_root
    )

    local -P length
    for var in $variables
        if [[ $#var -gt $length ]] length=$#var
    for var in $variables
        print "    ${(r:$length:)var}  ${(P)var}"
}
