#!/usr/bin/env zsh

fm() {
    setopt LOCAL_OPTIONS NO_SH_WORD_SPLIT EXTENDED_GLOB PIPE_FAIL NO_ALIASES NO_POSIX_IDENTIFIERS CLOBBER
    local -P cmd=${1:-run}
    if ! type fm::cmd-$cmd &>/dev/null; then
        fm::print -red "[FM ERROR] Unknown fm command '$cmd'!\n" >&2
        fm::cmd-help
        return 1
    fi
    if [[ $1 ]] shift
    fm::cmd-$cmd $@
}

