#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm() {
	setopt LOCAL_OPTIONS NO_SH_WORD_SPLIT EXTENDED_GLOB PIPE_FAIL NO_ALIASES NO_POSIX_IDENTIFIERS CLOBBER
	local -P cmd=${1:-run}
	if ! type fm__cmd-$cmd &>/dev/null; then
		fm__print -red "[FM ERROR] Unknown fm command '$cmd'!\n" >&2
		fm__cmd-help
		return 1
	fi
	if [[ $1 ]] shift
	fm__cmd-$cmd $@
}

