#!/usr/bin/env zsh

fm::cmd-help() {
	cat <<-HELP
		FM $fm_version - Copyright (c) 2020 Domizio Demichelis - dd.nexus@gmail.com

		USAGE
		    fm [COMMAND]

		COMMANDS
		    [run]                Open the FM Panel in \$PWD ("run" can be omitted)
		    -                    Jump-back to the \$PWD before FM was used
		    env                  Show the value of the relevant variables
		    add OPTS             Add your tool (command/function) in FM.
		                         See the "Added Tools" section in the FM Menu
		    compile              Compile all the FM functions for faster execution
		                         (wrapper around the executable fm-compile)
		    help                 Show this screen

		FAV WIDGET               FM provide a zsh widget to preview, navigate and pick
		                         and automatically place the selected items into the
		                         prompt line.
		FM_WIDGET_KEY            Variable to press for the widget shortcut key
		                        (defalt: press alt-f twice very fast)

		KEY OPTIONS              All the FM_KEY_* options are customizable shortcuts.
		                         They are linked to their respective menu entry in the
		                         FM Menu Panel. The FM_KEY_MENU, FM_KEY_VIEW_ITEM,
		                         FM_KEY_PREVIEW, FM_KEY_SELECT_ALL are essential and
		                         can be customized but not removed.
		                         All the other keys are also removable by setting them
		                         to "". In that case you can still pick their menu from
		                         the Menu Panel (and maybe use their key for more
		                         important or added menus)
		                         Select any FM Menu from the Menu Panel for details.

		CMD OPTIONS
		    FM_CMD_CAT           Preview command for files (support: bat|cat)
		    FM_CMD_LS            Command for listing dirs (support: exa|ls)
		    FM_CMD_FIND          Find command used in FM Panel list (support: fd|find)
		    FM_CMD_EDIT          EDITOR command for files
		    FM_CMD_OPEN          Open files/dirs with desktop command
		    FM_CMD_PAGER         Pager command used for File preview
		    FM_CMD_RIPGREP       Ripgrep command used for grep
		    FM_CMD_TERMINAL      New terminal session command (when no TMUX session found)
		    FM_CMD_SHELL         New shell command (when no FM_CMD_TERMINAL found) (*$SHELL)
		    FM_CMD_SUDO          Sudo command (can be disabled with "")
		    FM_CMD_STAT          Stat command or equivalent (for unhandled binary files preview)
		    FM_CMD_SORT          Sort command

		OTHER OPTIONS
		    FM_MAX_GREP_FILES    Max files with matches in GREP view
		    FM_MAX_RECENT_DIRS   Max recent dirs in REC view
		    FM_MAX_DIALOG_RECAP  Max lines shown in dialog recap
		    FM_MAX_MENU_RECAP    Max lines shown in menu recap
		    FM_MENU_WIDTH        Number of columns for the menu width (>= 34 COLUMNS)
		    FM_HINTS             Enable Hints message for menu shortcuts (*true|false)
		    FM_INFO_COLOR        fzf compilant color for prompt, info, preview header
		    FM_PREVIEW_MODES     Array of modes as understood by fzf --preview-window
		    FM_COMMAND_FZF_OPTS  Extra fzf options for the FM Command
		    FM_WIDGET_FZF_OPTS   Extra fzf options for the FM Widget
		    FM_DATA              Path to the FM data dir

		CURRENT ENVIRONMENT
		$(fm::cmd-env)

		DOCUMENTATION
		    https://github.com/ddnexus/fm
	HELP
}
