#!/usr/bin/env zsh

# Copyright (c) 2021 Domizio Demichelis
# Released under GNU3 license
# https://www.gnu.org/licenses/gpl-3.0.en.html


fm__cmd-help() {
	cat <<-HELP
		FM $fm__version - Copyright (c) 2020 Domizio Demichelis - dd.nexus@gmail.com

		USAGE
		    fm [COMMAND]

		COMMANDS
		    [run]                 Open the FM Panel in \$PWD ("run" can be omitted)
		    -                     Jump-back to the \$PWD before FM was used
		    env                   Show the value of the relevant variables
		    add OPTS              Add your tool (command/function) in FM.
		                          See the "Added Tools" section in the FM Menu
		    compile               Compile all the FM functions for faster execution
		                          (wrapper around the executable fm__compile)
		    help                  Show this screen

		FAV WIDGET                FM provide a zsh widget to preview, navigate and pick
		                          and automatically place the selected items into the
		                          prompt line.
		FM__WIDGET_KEY            Variable to press for the widget shortcut key
		                          (defalt: press alt-f twice very fast)

		KEY OPTIONS               All the FM__KEY_* options are customizable shortcuts.
		                          They are linked to their respective menu entry in the
		                          FM Menu Panel. The FM__KEY_MENU, FM__KEY_VIEW_ITEM,
		                          FM__KEY_PREVIEW, FM__KEY_SELECT_ALL are essential and
		                          can be customized but not removed.
		                          All the other keys are also removable by setting them
		                          to "". In that case you can still pick their menu from
		                          the Menu Panel (and maybe use their key for more
		                          important or added menus)
		                          Select any FM Menu from the Menu Panel for details.

		CMD OPTIONS
		    FM__CMD_CAT           Preview command for files (support: bat|cat)
		    FM__CMD_LS            Command for listing dirs (support: exa|ls)
		    FM__CMD_FIND          Find command used in FM Panel list (support: fd|find)
		    FM__CMD_EDIT          EDITOR command for files
		    FM__CMD_OPEN          Open files/dirs with desktop command
		    FM__CMD_PAGER         Pager command used for File preview
		    FM__CMD_RIPGREP       Ripgrep command used for grep
		    FM__CMD_TERMINAL      New terminal session command (when no TMUX session found)
		    FM__CMD_SHELL         New shell command (when no FM__CMD_TERMINAL found) (*$SHELL)
		    FM__CMD_SUDO          Sudo command (can be disabled with "")
		    FM__CMD_STAT          Stat command or equivalent (for unhandled binary files preview)
		    FM__CMD_SORT          Sort command

		OTHER OPTIONS
		    FM__MAX_GREP_FILES    Max files with matches in GREP view
		    FM__MAX_RECENT_DIRS   Max recent dirs in REC view
		    FM__MAX_DIALOG_RECAP  Max lines shown in dialog recap
		    FM__MAX_MENU_RECAP    Max lines shown in menu recap
		    FM__MENU_WIDTH        Number of columns for the menu width (>= 34 COLUMNS)
		    FM__HINTS             Enable Hints message for menu shortcuts (*true|false)
		    FM__INFO_COLOR        fzf compilant color for prompt, info, preview header
		    FM__PREVIEW_MODES     Array of modes as understood by fzf --preview-window
		    FM__COMMAND_FZF_OPTS  Extra fzf options for the FM Command
		    FM__WIDGET_FZF_OPTS   Extra fzf options for the FM Widget
		    FM__DATA              Path to the FM data dir

		CURRENT ENVIRONMENT
		$(fm__cmd-env)

		DOCUMENTATION
		    https://github.com/ddnexus/fm
	HELP
}
